version: "3.2"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net

  mysql:
    image: mysql:latest
    container_name: 'mysql'
    ports:
      - 3306:3306
    volumes:
      - ~/.docker-conf/mysql/data:/var/lib/mysql
      - ~/.docker-conf/mysql/conf:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: newpassword
      MYSQL_DATABASE: productio
      MYSQL_USER: root
      MYSQL_PASSWORD: newpassword
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge
