name: Go

on:
  pull_request:
    branches: [ main ]

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"

      - name: Build
        run: go build -v ./...
        
      - name: Test
        run: |
          sudo -E env "PATH=$PATH" ./Keploy test --c /tmp/Rocket/rocket --delay 2
        env:
          ENABLE_DEDUP: true
          ENABLE_TELEMETRY: false
